#!/usr/bin/env bash

# Change to directory of this script.
cd "$( dirname "${BASH_SOURCE[0]}" )"

# Look for existing vader installation.
vader=( ${HOME}/.vim/*bundle*/vader*/plugin/vader.vim )
if [ -f ${vader[0]} ]; then
    # Remove "plugin/vader.vim" suffix.
    vader=${vader[0]%/*/*}
fi

if [ -d $vader ]; then
    [[ ! -L vader.vim ]] && ln -s $vader vader.vim
else
    git clone https://github.com/junegunn/vader.vim.git
fi

echo '(Be patient.. testing can take a while.)'
vim -Nnu vimrc -i NONE +'Vader! feature/*.vader'
